## Data Preparation

#### Merging multiple csv files from the CitiBike datasource to prepare one dataset for Q1 2024 and one dataset for Q2 2024

In [25]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path

#### Q1 2024 data

In [26]:
# Load csv files
Jan_CB_df = pd.read_csv("Q1_2024/202401-citibike-tripdata.csv", dtype={5: "object", 7: "object"})
Feb_CB_df = pd.read_csv("Q1_2024/202402-citibike-tripdata.csv", dtype={5: "object", 7: "object"})
Mar_CB_df = pd.read_csv("Q1_2024/202403-citibike-tripdata.csv", dtype={5: "object", 7: "object"})

In [27]:
# Add a new column "month" with the value "January", "February", or "March"
Jan_CB_df['month'] = 'January'
Feb_CB_df['month'] = 'February'
Mar_CB_df['month'] = 'March'

In [28]:
# Concatenate the DataFrames along the rows
combined_Q1_df = pd.concat([Jan_CB_df, Feb_CB_df, Mar_CB_df], ignore_index=True)

# View the combined dataframe
combined_Q1_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,month
0,5078F3D302000BD2,electric_bike,2024-01-22 18:43:19.012,2024-01-22 18:48:10.708,Frederick Douglass Blvd & W 145 St,7954.12,St Nicholas Ave & W 126 St,7756.10,40.823072,-73.941738,40.811432,-73.951878,member,January
1,814337105D37302A,electric_bike,2024-01-11 19:19:18.721,2024-01-11 19:47:36.007,W 54 St & 6 Ave,6771.13,E 74 St & 1 Ave,6953.08,40.761822,-73.977036,40.768974,-73.954823,member,January
2,A33A920E2B10710C,electric_bike,2024-01-30 19:17:41.693,2024-01-30 19:32:49.857,E 11 St & Ave B,5659.11,W 10 St & Washington St,5847.06,40.727592,-73.979751,40.733424,-74.008515,casual,January
3,A3A5FC0DD7D34D74,electric_bike,2024-01-27 11:27:01.759,2024-01-27 11:38:01.213,W 54 St & 6 Ave,6771.13,E 74 St & 1 Ave,6953.08,40.761779,-73.977144,40.768974,-73.954823,member,January
4,6F96728ECEFBDAA4,electric_bike,2024-01-16 15:15:41.000,2024-01-16 15:29:26.156,Madison Ave & E 99 St,7443.01,E 74 St & 1 Ave,6953.08,40.789808,-73.952214,40.768974,-73.954823,member,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6672876,D294FEC7F31CBA54,electric_bike,2024-03-15 11:44:14.141,2024-03-15 12:00:56.277,W 15 St & 10 Ave,6115.09,W 67 St & Broadway,7116.04,40.742574,-74.007304,40.774925,-73.982666,member,March
6672877,F96260F790F4EC76,electric_bike,2024-03-18 16:50:23.185,2024-03-18 17:21:28.465,W 15 St & 10 Ave,6115.09,Lafayette Ave & St James Pl,4494.04,40.742519,-74.007241,40.688515,-73.964763,member,March
6672878,92D52DD10562A799,electric_bike,2024-03-20 11:35:21.922,2024-03-20 11:41:43.275,India St & Manhattan Ave,5826.02,N 9 St & Wythe Ave,5489.06,40.731635,-73.954247,40.720540,-73.959000,member,March
6672879,CEA7A7CA104EDB3A,electric_bike,2024-03-15 09:29:16.009,2024-03-15 09:35:20.455,India St & Manhattan Ave,5826.02,N 9 St & Wythe Ave,5489.06,40.732364,-73.955142,40.720540,-73.959000,member,March
6672880,BB74320171FA7163,classic_bike,2024-03-18 14:51:20.408,2024-03-18 14:57:51.304,W 31 St & 7 Ave,6331.01,E 32 St & Park Ave,6280.12,40.749156,-73.991600,40.745712,-73.981948,member,March

In [30]:
# Drop duplicate columns, if any
combined_Q1_df = combined_Q1_df.loc[:, ~combined_Q1_df.columns.duplicated()]

# View the combined dataframe
combined_Q1_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,month
0,5078F3D302000BD2,electric_bike,2024-01-22 18:43:19.012,2024-01-22 18:48:10.708,Frederick Douglass Blvd & W 145 St,7954.12,St Nicholas Ave & W 126 St,7756.10,40.823072,-73.941738,40.811432,-73.951878,member,January
1,814337105D37302A,electric_bike,2024-01-11 19:19:18.721,2024-01-11 19:47:36.007,W 54 St & 6 Ave,6771.13,E 74 St & 1 Ave,6953.08,40.761822,-73.977036,40.768974,-73.954823,member,January
2,A33A920E2B10710C,electric_bike,2024-01-30 19:17:41.693,2024-01-30 19:32:49.857,E 11 St & Ave B,5659.11,W 10 St & Washington St,5847.06,40.727592,-73.979751,40.733424,-74.008515,casual,January
3,A3A5FC0DD7D34D74,electric_bike,2024-01-27 11:27:01.759,2024-01-27 11:38:01.213,W 54 St & 6 Ave,6771.13,E 74 St & 1 Ave,6953.08,40.761779,-73.977144,40.768974,-73.954823,member,January
4,6F96728ECEFBDAA4,electric_bike,2024-01-16 15:15:41.000,2024-01-16 15:29:26.156,Madison Ave & E 99 St,7443.01,E 74 St & 1 Ave,6953.08,40.789808,-73.952214,40.768974,-73.954823,member,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6672876,D294FEC7F31CBA54,electric_bike,2024-03-15 11:44:14.141,2024-03-15 12:00:56.277,W 15 St & 10 Ave,6115.09,W 67 St & Broadway,7116.04,40.742574,-74.007304,40.774925,-73.982666,member,March
6672877,F96260F790F4EC76,electric_bike,2024-03-18 16:50:23.185,2024-03-18 17:21:28.465,W 15 St & 10 Ave,6115.09,Lafayette Ave & St James Pl,4494.04,40.742519,-74.007241,40.688515,-73.964763,member,March
6672878,92D52DD10562A799,electric_bike,2024-03-20 11:35:21.922,2024-03-20 11:41:43.275,India St & Manhattan Ave,5826.02,N 9 St & Wythe Ave,5489.06,40.731635,-73.954247,40.720540,-73.959000,member,March
6672879,CEA7A7CA104EDB3A,electric_bike,2024-03-15 09:29:16.009,2024-03-15 09:35:20.455,India St & Manhattan Ave,5826.02,N 9 St & Wythe Ave,5489.06,40.732364,-73.955142,40.720540,-73.959000,member,March
6672880,BB74320171FA7163,classic_bike,2024-03-18 14:51:20.408,2024-03-18 14:57:51.304,W 31 St & 7 Ave,6331.01,E 32 St & Park Ave,6280.12,40.749156,-73.991600,40.745712,-73.981948,member,March

In [31]:
# Save the combined DataFrame to a new CSV file
combined_Q1_df.to_csv("combined_Q1_2024_data.csv", index=False)

#### Q2 2024 data

In [32]:
# Load the csv files
Apr_CB_df = pd.read_csv("Q2_2024/202404-citibike-tripdata.csv", dtype={5: "object", 7: "object"})
May_1_CB_df = pd.read_csv("Q2_2024/202405-citibike-tripdata_1.csv", dtype={5: "object", 7: "object"})
May_2_CB_df = pd.read_csv("Q2_2024/202405-citibike-tripdata_2.csv", dtype={5: "object", 7: "object"})
May_3_CB_df = pd.read_csv("Q2_2024/202405-citibike-tripdata_3.csv", dtype={5: "object", 7: "object"})
May_4_CB_df = pd.read_csv("Q2_2024/202405-citibike-tripdata_4.csv", dtype={5: "object", 7: "object"})
May_5_CB_df = pd.read_csv("Q2_2024/202405-citibike-tripdata_5.csv", dtype={5: "object", 7: "object"})
Jun_1_CB_df = pd.read_csv("Q2_2024/202406-citibike-tripdata_1.csv", dtype={5: "object", 7: "object"})
Jun_2_CB_df = pd.read_csv("Q2_2024/202406-citibike-tripdata_2.csv", dtype={5: "object", 7: "object"})
Jun_3_CB_df = pd.read_csv("Q2_2024/202406-citibike-tripdata_3.csv", dtype={5: "object", 7: "object"})
Jun_4_CB_df = pd.read_csv("Q2_2024/202406-citibike-tripdata_4.csv", dtype={5: "object", 7: "object"})
Jun_5_CB_df = pd.read_csv("Q2_2024/202406-citibike-tripdata_5.csv", dtype={5: "object", 7: "object"})

In [33]:
# Add a new column "month" with the value "April"
Apr_CB_df['month'] = 'April'

In [34]:
# Concatenate the May DataFrames along the rows
combined_May_df = pd.concat([May_1_CB_df, May_2_CB_df, May_3_CB_df, May_4_CB_df, May_5_CB_df], ignore_index=True)

# View the combined dataframe
combined_May_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,FE6A074FC945A086,electric_bike,2024-05-01 08:05:53,2024-05-01 08:15:14,1 Ave & E 30 St,6079.03,E 74 St & 1 Ave,6953.08,40.741509,-73.975355,40.768974,-73.954823,member
1,6844CF42F72827D7,classic_bike,2024-05-10 15:00:06,2024-05-10 15:08:58,31 Ave & 57 St,6621.06,31 Ave & Steinway St,6782.01,40.757357,-73.904726,40.761149,-73.917007,member
2,D7C9E007F791A7A2,classic_bike,2024-05-06 12:28:39,2024-05-06 12:35:21,E 89 St & 3 Ave,7265.10,E 80 St & 2 Ave,7121.02,40.780628,-73.952167,40.773914,-73.954395,member
3,3419650E2F5999F1,classic_bike,2024-05-16 16:09:14,2024-05-16 16:14:20,E 89 St & 3 Ave,7265.10,E 80 St & 2 Ave,7121.02,40.780628,-73.952167,40.773914,-73.954395,member
4,5469FDC75E0F1FCA,electric_bike,2024-05-29 15:43:37,2024-05-29 15:49:27,1 Ave & E 30 St,6079.03,E 45 St & 3 Ave,6464.08,40.741444,-73.975361,40.752554,-73.972826,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4230355,EA8D2DB4B6B01F2E,classic_bike,2024-05-16 15:03:40,2024-05-16 15:27:14,West St & Chambers St,5329.03,11 Ave & W 41 St,6726.01,40.717548,-74.013221,40.760301,-73.998842,member
4230356,B4B7E3EC2DDDD247,electric_bike,2024-05-14 14:35:08,2024-05-14 14:48:28,West St & Chambers St,5329.03,11 Ave & W 41 St,6726.01,40.717733,-74.013023,40.760301,-73.998842,member
4230357,4C646AB4A67E7365,classic_bike,2024-05-06 14:11:31,2024-05-06 14:31:30,West St & Chambers St,5329.03,11 Ave & W 41 St,6726.01,40.717548,-74.013221,40.760301,-73.998842,member
4230358,73EE4AE1389EF161,electric_bike,2024-05-24 18:52:49,2024-05-24 19:01:37,Bushwick Ave & Powers St,5250.05,Bedford Ave & Nassau Ave,5550.05,40.712562,-73.941067,40.723117,-73.952123,member
4230359,38695F4EFCA5BD75,electric_bike,2024-05-27 09:43:17,2024-05-27 09:50:46,Willoughby Ave & Walworth St,4634.02,Willoughby Ave & Myrtle Ave,4759.02,40.693206,-73.953851,40.697570,-73.930980,member

In [35]:
# Add a new column "month" with the value "May"
combined_May_df['month'] = 'May'

In [37]:
# Concatenate the June DataFrames along the rows
combined_Jun_df = pd.concat([Jun_1_CB_df, Jun_2_CB_df, Jun_3_CB_df, Jun_4_CB_df, Jun_5_CB_df], ignore_index=True)

# View the combined dataframe
combined_Jun_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,A38B171B6C31691A,electric_bike,2024-06-12 17:47:23.952,2024-06-12 17:50:27.312,E 89 St & 3 Ave,7265.10,1 Ave & E 94 St,7286.05,40.780499,-73.952185,40.781721,-73.945940,member
1,77E13C9D6559EA56,electric_bike,2024-06-04 16:48:42.876,2024-06-04 17:01:46.672,Pier 40 - Hudson River Park,5696.03,W 25 St & 9 Ave,6339.06,40.728060,-74.011184,40.747833,-74.000572,member
2,EA6418AD826D19D9,electric_bike,2024-06-01 13:36:28.502,2024-06-01 13:52:55.912,W 44 St & 5 Ave,6551.02,E 75 St & 3 Ave,6991.12,40.754621,-73.980641,40.771129,-73.957723,member
3,121CF2548FB65A29,classic_bike,2024-06-01 03:12:09.636,2024-06-01 03:16:29.531,Graham Ave & Withers St,5403.04,Meserole Ave & Manhattan Ave,5666.04,40.716981,-73.944859,40.727086,-73.952991,member
4,E6BE7FD2809649D6,electric_bike,2024-06-08 13:14:31.197,2024-06-08 13:24:09.858,E 9 St & Ave C,5616.01,Cleveland Pl & Spring St,5492.05,40.725241,-73.977735,40.722104,-73.997249,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4783571,DA8BFCDCEAA4957D,classic_bike,2024-06-20 20:28:52.400,2024-06-20 20:35:01.668,W 44 St & 5 Ave,6551.02,E 32 St & Park Ave,6280.12,40.755003,-73.980144,40.745712,-73.981948,member
4783572,AE41AD4BA8B90E02,electric_bike,2024-06-16 15:12:54.352,2024-06-16 15:25:20.425,6 Ave & Canal St,5500.07,E 6 St & Ave B,5584.04,40.722389,-74.005717,40.724537,-73.981854,casual
4783573,90F1ADD977F5C19C,classic_bike,2024-06-22 07:05:04.662,2024-06-22 08:15:09.620,6 Ave & Canal St,5500.07,West St & Liberty St,5184.08,40.722438,-74.005664,40.711444,-74.014847,casual
4783574,0C16F8490B79B111,electric_bike,2024-06-21 10:23:38.519,2024-06-21 10:33:29.781,W 13 St & 5 Ave,5947.04,E 32 St & Park Ave,6280.12,40.735384,-73.994781,40.745712,-73.981948,member
4783575,4F12C3CEDA945FB7,electric_bike,2024-06-16 15:51:40.807,2024-06-16 16:15:27.501,Berkeley Pl & 7 Ave,4051.01,N 5 St & Northside Piers,5458.02,40.675166,-73.975224,40.719876,-73.963865,member

In [38]:
# Add a new column "month" with the value "May"
combined_Jun_df['month'] = 'June'

In [40]:
# Concatenate the Q2 DataFrames along the rows
combined_Q2_df = pd.concat([Apr_CB_df, combined_May_df, combined_Jun_df], ignore_index=True)

# View the combined dataframe
combined_Q2_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,month
0,F561526822C9D60B,electric_bike,2024-04-27 13:56:13.940,2024-04-27 14:05:23.629,FDR Drive & E 35 St,6230.04,E 10 St & 2 Ave,5746.02,40.743955,-73.971391,40.729708,-73.986598,member,April
1,359BAF91507F4998,electric_bike,2024-04-25 15:23:14.529,2024-04-25 15:27:52.895,Forsyth St & Grand St,5382.07,E 10 St & 2 Ave,5746.02,40.717741,-73.993388,40.729708,-73.986598,member,April
2,AAEE95A1C0106C97,electric_bike,2024-04-06 11:15:18.132,2024-04-06 11:22:10.081,E 20 St & 2 Ave,5971.08,Mott St & Prince St,5561.04,40.735790,-73.981693,40.723180,-73.994800,member,April
3,95B077C9C619D404,electric_bike,2024-04-06 16:19:25.749,2024-04-06 16:21:43.098,Eastern Pkwy & Washington Ave,3928.08,Eastern Pkwy & Franklin Ave (SW Corner),3919.12,40.671649,-73.963115,40.670529,-73.958222,member,April
4,1A33C864454C4692,electric_bike,2024-04-10 17:40:14.700,2024-04-10 17:48:11.571,W 27 St & 6 Ave,6215.07,E 25 St & 1 Ave,6004.07,40.745446,-73.990591,40.738177,-73.977387,member,April
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12230994,DA8BFCDCEAA4957D,classic_bike,2024-06-20 20:28:52.400,2024-06-20 20:35:01.668,W 44 St & 5 Ave,6551.02,E 32 St & Park Ave,6280.12,40.755003,-73.980144,40.745712,-73.981948,member,June
12230995,AE41AD4BA8B90E02,electric_bike,2024-06-16 15:12:54.352,2024-06-16 15:25:20.425,6 Ave & Canal St,5500.07,E 6 St & Ave B,5584.04,40.722389,-74.005717,40.724537,-73.981854,casual,June
12230996,90F1ADD977F5C19C,classic_bike,2024-06-22 07:05:04.662,2024-06-22 08:15:09.620,6 Ave & Canal St,5500.07,West St & Liberty St,5184.08,40.722438,-74.005664,40.711444,-74.014847,casual,June
12230997,0C16F8490B79B111,electric_bike,2024-06-21 10:23:38.519,2024-06-21 10:33:29.781,W 13 St & 5 Ave,5947.04,E 32 St & Park Ave,6280.12,40.735384,-73.994781,40.745712,-73.981948,member,June
12230998,4F12C3CEDA945FB7,electric_bike,2024-06-16 15:51:40.807,2024-06-16 16:15:27.501,Berkeley Pl & 7 Ave,4051.01,N 5 St & Northside Piers,5458.02,40.675166,-73.975224,40.719876,-73.963865,member,June

In [41]:
# Drop duplicate columns, if any
combined_Q2_df = combined_Q2_df.loc[:, ~combined_Q2_df.columns.duplicated()]

# View the combined dataframe
combined_Q2_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,month
0,F561526822C9D60B,electric_bike,2024-04-27 13:56:13.940,2024-04-27 14:05:23.629,FDR Drive & E 35 St,6230.04,E 10 St & 2 Ave,5746.02,40.743955,-73.971391,40.729708,-73.986598,member,April
1,359BAF91507F4998,electric_bike,2024-04-25 15:23:14.529,2024-04-25 15:27:52.895,Forsyth St & Grand St,5382.07,E 10 St & 2 Ave,5746.02,40.717741,-73.993388,40.729708,-73.986598,member,April
2,AAEE95A1C0106C97,electric_bike,2024-04-06 11:15:18.132,2024-04-06 11:22:10.081,E 20 St & 2 Ave,5971.08,Mott St & Prince St,5561.04,40.735790,-73.981693,40.723180,-73.994800,member,April
3,95B077C9C619D404,electric_bike,2024-04-06 16:19:25.749,2024-04-06 16:21:43.098,Eastern Pkwy & Washington Ave,3928.08,Eastern Pkwy & Franklin Ave (SW Corner),3919.12,40.671649,-73.963115,40.670529,-73.958222,member,April
4,1A33C864454C4692,electric_bike,2024-04-10 17:40:14.700,2024-04-10 17:48:11.571,W 27 St & 6 Ave,6215.07,E 25 St & 1 Ave,6004.07,40.745446,-73.990591,40.738177,-73.977387,member,April
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12230994,DA8BFCDCEAA4957D,classic_bike,2024-06-20 20:28:52.400,2024-06-20 20:35:01.668,W 44 St & 5 Ave,6551.02,E 32 St & Park Ave,6280.12,40.755003,-73.980144,40.745712,-73.981948,member,June
12230995,AE41AD4BA8B90E02,electric_bike,2024-06-16 15:12:54.352,2024-06-16 15:25:20.425,6 Ave & Canal St,5500.07,E 6 St & Ave B,5584.04,40.722389,-74.005717,40.724537,-73.981854,casual,June
12230996,90F1ADD977F5C19C,classic_bike,2024-06-22 07:05:04.662,2024-06-22 08:15:09.620,6 Ave & Canal St,5500.07,West St & Liberty St,5184.08,40.722438,-74.005664,40.711444,-74.014847,casual,June
12230997,0C16F8490B79B111,electric_bike,2024-06-21 10:23:38.519,2024-06-21 10:33:29.781,W 13 St & 5 Ave,5947.04,E 32 St & Park Ave,6280.12,40.735384,-73.994781,40.745712,-73.981948,member,June
12230998,4F12C3CEDA945FB7,electric_bike,2024-06-16 15:51:40.807,2024-06-16 16:15:27.501,Berkeley Pl & 7 Ave,4051.01,N 5 St & Northside Piers,5458.02,40.675166,-73.975224,40.719876,-73.963865,member,June

In [ ]:
# Save the combined DataFrame to a new CSV file
combined_Q2_df.to_csv("combined_Q2_2024_data.csv", index=False)